FROM ubuntu:latest
WORKDIR /etc/algomon/api-caller

# Install wget
RUN apt-get update && apt-get upgrade -y && \
	apt-get install -y wget curl cron jq >/proc/1/fd/1 2>/proc/1/fd/2

# Install yq
RUN wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq >/proc/1/fd/1 2>/proc/1/fd/2

RUN ( echo '@reboot bash /etc/algomon/api-caller/startup.sh >/proc/1/fd/1 2>/proc/1/fd/2'; \
	echo '* * * * * bash /etc/algomon/api-caller/algonode-api-caller.sh >/proc/1/fd/1 2>/proc/1/fd/2'; ) | \
	crontab - >/proc/1/fd/1 2>/proc/1/fd/2

CMD ["cron", "-f"]
