FROM grafana/grafana:latest

RUN mkdir -p /var/lib/grafana/dashboards
RUN mkdir -p /usr/share/grafana/public/maps

COPY ./datasource-manifest.yaml /etc/grafana/provisioning/datasources/default.yaml
COPY ./dashboard-provider.yaml /etc/grafana/provisioning/dashboards/default.yaml
