FROM docker.elastic.co/elasticsearch/elasticsearch:6.8.23
#USER root

# Install cron   
# RUN yum -y update && yum -y install cronie;
# RUN yum -y install cronie;

# Install yq
# RUN wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq;

# Install jq
# RUN wget https://github.com/jqlang/jq/releases/download/jq-1.7/jq-linux-amd64 -O /usr/bin/jq && chmod +x /usr/bin/jq;

# Create cron job to run algonode-api-caller
# RUN touch /etc/crontab /etc/cron.*/*;
# RUN cron_cmd="/usr/share/elasticsearch/config/algonode-api-caller.sh >> /var/log/cron.log 2>&1" &&\
# RUN chmod 0744 /usr/share/elasticsearch/config/algonode-api-caller.sh
# RUN cron_cmd="/usr/share/elasticsearch/config/algonode-api-caller.sh > /proc/1/fd/1 2>/proc/1/fd/2" &&\
#    cron_schedule="* * * * *" &&\
#    cron_job="${cron_schedule} ${cron_cmd}";
    # crontab <<<"${cron_job}";

# RUN ( /usr/bin/crontab -l | grep -v -F "${cron_cmd}" || : ; echo "${cron_job}" ) | /usr/bin/crontab -

# CMD ["cron", "-f"]

#RUN cat <<-// >> /etc/cron.d/elasticsearch-cron
#    * * * * * /usr/share/elasticsearch/config/algonode-api-caller.sh >> /var/log/cron.log 2>&1
#//

# RUN chmod 0644 /etc/cron.d/elasticsearch-cron
# RUN touch /var/log/cron.log

# CMD cron && tail -f /var/log/cron.log

# Create the service file
#RUN cat <<-// >> /etc/systemd/system/algonode-api-caller.service
#   [Unit]
#   Description="Runs the algonode api caller, publishing responses to the local Elasticsearch instance"
   #Wants=network-online.target
   #After=network-online.target
#   After=docker.service
#   After=elasticsearch.service
#   Requires=docker.service
#   Requires=elasticsearch.service
#   Wants=algonode-api-caller.timer

#   [Service]
#   SyslogIdentifier=ALGONODE-API-CALLER
   #ExecStart=/bin/bash /usr/share/elasticsearch/config/algonode-api-calls.sh
#   ExecStart=/bin/docker run --rm -name %n /usr/share/elasticsearch/config/algonode-api-calls.sh
#   ExecStop=/bin/docker stop %n
#   Restart=on-failure
#   RestartSec=5s
#   User=root

#   [Install]
#   WantedBy=multi-user.target
#//

# Create the timer file
#RUN cat <<-// >> /etc/systemd/system/algonode-api-caller.timer
#   [Unit]
#   Description="Timer to run the algonode api caller service"
#   Requires=algonode-api-caller.service

#   [Timer]
#   Unit=algonode-api-caller.service
#   OnCalendar=*:*:0/15 # run the target every 15 seconds

#   [Install]
#   WantedBy=timers.target
#//

#RUN systemctl daemon-reload && systemctl start algonode-api-caller
